import { Product } from "@/types/products";

export const products: Product[] = [
  {
    title: "UrbanTwin - Intelligent Urban Visualization",
    description:
      "An intelligent, living visualization of urban data. UrbanTwin transforms static maps into a volumetric 3D digital twin with realistic terrain, atmospheric effects, and AI-powered insights.",
    thumbnail: "/urban twin.png",
    images: ["/urban twin.png"],
    href: "https://urban-twin.vercel.app/",
    github: "https://github.com/swastideep-maharana/UrbanTwin",
    stack: ["Next.js", "TypeScript", "Mapbox GL JS", "Gemini API", "Tailwind CSS"],
    slug: "urban-twin",
    color: "from-blue-500 to-cyan-500",
    content: `UrbanTwin is not just a map; it’s an intelligent, living visualization of urban data. Built with Next.js 15 and Mapbox GL JS, it features a volumetric 3D digital twin with realistic terrain and atmospheric sky layers. Powered by the Google Gemini API, it provides intelligent insights into urban environments. [Live](https://urban-twin.vercel.app/) | [GitHub](https://github.com/swastideep-maharana/UrbanTwin)`,
  },
  {
    title: "Pixxel-ai - AI Image Editor",
    description:
      " Pixxel-ai is a cutting-edge AI image editor that allows users to enhance and transform their images with ease. Features include AI-powered image enhancement, background removal, and a user-friendly interface built with Tailwind CSS.",
    thumbnail: "/pixxel.png",
    images: ["/pixxel.png"],
    href: "https://pixxel-ai-image-editor.vercel.app/",
    github: "https://github.com/swastideep-maharana/Pixxel-ai",
    stack: ["React", "Node.js", "MongoDB", "Express", "Tailwind CSS"],
    slug: "tomato",
    color: "from-purple-500 to-pink-500",
    content: `Pixxel-ai is an advanced AI image editor that simplifies the process of enhancing and transforming images. With features like AI-powered enhancement, background removal, and a sleek user interface, Pixxel-ai makes image editing accessible to everyone.  `,
  },
  {
    title: "Storelt",
    description:
      "Storelt is a powerful, easy-to-use web application that allows you to upload, share, and manage your documents seamlessly. Whether you're looking for something similar to Google Drive or Dropbox, Storelt has you covered! Features include document upload, sharing via email, real-time search, secure OTP login, and a user-friendly UI built with Tailwind CSS.",
    thumbnail: "/storelt.png",
    images: ["/storelt.png"],
    href: "https://storelt-drive.vercel.app/sign-in",
    github: "https://github.com/swastideep-maharana/Storelt-Drive",
    stack: ["Next.js", "TypeScript", "Appwrite", "Tailwind CSS", "Vercel"],
    slug: "storelt",
    color: "from-indigo-500 to-blue-600",
    content: `Storelt is your personal document manager, offering seamless upload, sharing, and management of files. With secure OTP authentication, real-time search, and a clean UI, Storelt is the only store you need—just like Google Drive. [Live](https://storelt-drive.vercel.app/sign-in) | [GitHub](https://github.com/swastideep-maharana/Storelt-Drive)`,
  },
  {
    title: "AI Tutor - Learning Companion",
    description:
      "An AI-powered learning platform that provides personalized tutoring and voice interaction. Features include interactive learning sessions, voice-enabled AI companions, and adaptive learning paths.",
    thumbnail: "/Ai-Tutor.png",
    images: ["/Ai-Tutor.png"],
    href: "https://ai-voice-agent-interview-prep-4ztc.vercel.app",
    github:
      "https://github.com/swastideep-maharana/AI-Voice-Agent-Interview-Prep",
    stack: ["Next.js", "TypeScript", "OpenAI", "Tailwind CSS", "Vercel"],
    slug: "ai-tutor",
    content: `AI Tutor is an innovative learning platform that leverages artificial intelligence to provide personalized educational experiences. The platform features voice-enabled AI companions that adapt to each user's learning style, offering interactive sessions and real-time feedback. Built with Next.js and TypeScript, it provides a seamless and engaging learning environment for users of all levels.`,
  },
  
  {
    title: "Movie-app",
    description:
      "A modern movie discovery web application that helps users find trending and popular movies with ease. Features include trending movies, search functionality, and a visually appealing UI. Built with React and Vite for fast performance.",
    thumbnail: "/movie app.png",
    images: ["/movie app.png"],
    href: "https://movie-app-nu-ruddy.vercel.app/",
    github: "https://github.com/swastideep-maharana/Movie-app",
    stack: ["React", "Vite", "JavaScript", "CSS"],
    slug: "movie-app",
    content: `Movie-app is a sleek and user-friendly platform for discovering trending and popular movies. Users can search through thousands of movies, view trending lists, and enjoy a beautiful, responsive interface. [Live](https://movie-app-nu-ruddy.vercel.app/) | [GitHub](https://github.com/swastideep-maharana/Movie-app)`,
  },
  {
    title: "ChatterBox - Real-time Chat Application",
    description:
      "A modern real-time chat application supporting individual and group conversations. Features include instant messaging, user authentication, message history, and real-time notifications.",
    thumbnail: "/chatterbox.png",
    images: ["/chatterbox.png"],
    href: "https://chatterbox-1qmd.onrender.com",
    github: "https://github.com/swastideep-maharana/ChatterBox",
    stack: ["React", "Node.js", "MongoDB", "Socket.io", "Express"],
    slug: "chatterbox",
    content: `ChatterBox is a feature-rich real-time chat application that enables seamless communication between users. The platform supports both individual and group conversations, with features like message history, real-time notifications, and user authentication. Built with modern web technologies for optimal performance and reliability.`,
  },
  {
    title: "BinkeyIt - E-commerce Platform",
    description:
      "A comprehensive e-commerce platform with features like product catalog, shopping cart, user authentication, payment processing, and order management. Built with modern web technologies for optimal performance.",
    thumbnail: "/binkeyit.png",
    images: ["/binkeyit.png"],
    href: "https://binkeyit-ecommercee.vercel.app",
    stack: ["React", "Node.js", "MongoDB", "Express", "Tailwind CSS"],
    slug: "binkeyit",
    content: `BinkeyIt is a full-featured e-commerce platform that provides a seamless shopping experience. The platform includes a comprehensive product catalog, secure shopping cart functionality, user authentication, and integrated payment processing. Built with modern web technologies for optimal performance and user experience.`,
  },
  {
    title: "BuildIX - AI-Powered Web App Builder",
    description:
      "An innovative platform that enables users to create full-stack web applications using AI as a backend. Features include drag-and-drop interface, AI-powered code generation, and real-time preview.",
    thumbnail: "/buildix.png",
    images: ["/buildix.png"],
    href: "https://buildix.netlify.app",
    stack: ["React", "TypeScript", "MongoDB", "AI Integration"],
    slug: "buildix",
    content: `BuildIX is an innovative platform that revolutionizes web application development through AI integration. Users can create full-stack applications using an intuitive drag-and-drop interface, with AI-powered code generation and real-time preview capabilities. The platform makes web development accessible to users of all skill levels.`,
  },
  {
    title: "RespawinGalaxy - Gaming Website",
    description:
      "An interactive gaming website showcasing the dynamic world of gaming. Features include game listings, user profiles, community features, and an immersive user interface.",
    thumbnail: "/respawing.png",
    images: ["/respawing.png"],
    href: "https://respawingalaxy.netlify.app",
    stack: ["React", "JavaScript", "HTML", "CSS", "Tailwind CSS"],
    slug: "respawingalaxy",
    content: `RespawinGalaxy is an immersive gaming platform that brings together gaming enthusiasts from around the world. The website features an extensive collection of games, user profiles, community features, and an engaging user interface. Players can discover new games, connect with other gamers, and share their gaming experiences.`,
  },
  {
    title: "NovaShield - SaaS Landing Page",
    description: "NovaShield is a high-conversion SaaS landing page built with React, Tailwind CSS, and Framer Motion. Designed for AI, Web3, and SaaS startups, it focuses on clarity, trust, and conversion.",
    thumbnail: "/Novashield.png",
    images: ["/Novashield.png"],
    href: "https://nova-shield-eosin.vercel.app/",
    github: "https://github.com/swastideep-maharana/NovaShield",
    stack: ["React", "Tailwind CSS", "Framer Motion", "SaaS"],
    slug: "novashield",
    content: `NovaShield is a high-conversion SaaS landing page built with React, Tailwind CSS, and Framer Motion. Designed for AI, Web3, and SaaS startups, it focuses on clarity, trust, and conversion using modern UI patterns, smooth animations, and scalable components. [Live](https://nova-shield-eosin.vercel.app/) | [GitHub](https://github.com/swastideep-maharana/NovaShield)`,
  },
  {
    title: "Swirlzy - D2C Bakery Landing Page",
    description: "Swirlzy is a modern D2C landing page for food and bakery brands, built using React and Tailwind CSS. It focuses on visual storytelling and product discovery.",
    thumbnail: "/Swirlzy.png",
    images: ["/Swirlzy.png"],
    href: "https://swirlzy-jade.vercel.app/",
    github: "https://github.com/swastideep-maharana/Swirlzy",
    stack: ["React", "Tailwind CSS", "D2C", "Bakery"],
    slug: "swirlzy",
    content: `Swirlzy is a modern D2C landing page for food and bakery brands, built using React and Tailwind CSS. It focuses on visual storytelling, product discovery, and conversion-driven design with smooth interactions. [Live](https://swirlzy-jade.vercel.app/) | [GitHub](https://github.com/swastideep-maharana/Swirlzy)`,
  },
];
